package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG_ENTITY.
 */
public class ConfigEntity {

    private Long id;
    private String sid;
    private Short currentStudent;
    private String username;
    private String password;

    public ConfigEntity() {
    }

    public ConfigEntity(Long id) {
        this.id = id;
    }

    public ConfigEntity(Long id, String sid, Short currentStudent, String username, String password) {
        this.id = id;
        this.sid = sid;
        this.currentStudent = currentStudent;
        this.username = username;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public Short getCurrentStudent() {
        return currentStudent;
    }

    public void setCurrentStudent(Short currentStudent) {
        this.currentStudent = currentStudent;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
