package com.guokrspace.cloudschoolbus.parents.database.daodb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configEntityDaoConfig;
    private final DaoConfig studentEntityDaoConfig;

    private final ConfigEntityDao configEntityDao;
    private final StudentEntityDao studentEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configEntityDaoConfig = daoConfigMap.get(ConfigEntityDao.class).clone();
        configEntityDaoConfig.initIdentityScope(type);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        configEntityDao = new ConfigEntityDao(configEntityDaoConfig, this);
        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);

        registerDao(ConfigEntity.class, configEntityDao);
        registerDao(StudentEntity.class, studentEntityDao);
    }
    
    public void clear() {
        configEntityDaoConfig.getIdentityScope().clear();
        studentEntityDaoConfig.getIdentityScope().clear();
    }

    public ConfigEntityDao getConfigEntityDao() {
        return configEntityDao;
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

}
