package com.guokrspace.cloudschoolbus.parents.database.daodb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configEntityDaoConfig;
    private final DaoConfig studentEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;
    private final DaoConfig classEntityDaoConfig;
    private final DaoConfig schoolEntityDaoConfig;
    private final DaoConfig messageBodyEntityDaoConfig;
    private final DaoConfig senderEntityDaoConfig;
    private final DaoConfig tagEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig articleEntityDaoConfig;
    private final DaoConfig imageEntityDaoConfig;
    private final DaoConfig attendanceEntityDaoConfig;
    private final DaoConfig festivalEntityDaoConfig;
    private final DaoConfig scheduleEntityDaoConfig;
    private final DaoConfig lastLetterEntityDaoConfig;
    private final DaoConfig letterEntityDaoConfig;
    private final DaoConfig reportEntityDaoConfig;
    private final DaoConfig reportItemEntityDaoConfig;

    private final ConfigEntityDao configEntityDao;
    private final StudentEntityDao studentEntityDao;
    private final TeacherEntityDao teacherEntityDao;
    private final ClassEntityDao classEntityDao;
    private final SchoolEntityDao schoolEntityDao;
    private final MessageBodyEntityDao messageBodyEntityDao;
    private final SenderEntityDao senderEntityDao;
    private final TagEntityDao tagEntityDao;
    private final MessageEntityDao messageEntityDao;
    private final ArticleEntityDao articleEntityDao;
    private final ImageEntityDao imageEntityDao;
    private final AttendanceEntityDao attendanceEntityDao;
    private final FestivalEntityDao festivalEntityDao;
    private final ScheduleEntityDao scheduleEntityDao;
    private final LastLetterEntityDao lastLetterEntityDao;
    private final LetterEntityDao letterEntityDao;
    private final ReportEntityDao reportEntityDao;
    private final ReportItemEntityDao reportItemEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configEntityDaoConfig = daoConfigMap.get(ConfigEntityDao.class).clone();
        configEntityDaoConfig.initIdentityScope(type);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        classEntityDaoConfig = daoConfigMap.get(ClassEntityDao.class).clone();
        classEntityDaoConfig.initIdentityScope(type);

        schoolEntityDaoConfig = daoConfigMap.get(SchoolEntityDao.class).clone();
        schoolEntityDaoConfig.initIdentityScope(type);

        messageBodyEntityDaoConfig = daoConfigMap.get(MessageBodyEntityDao.class).clone();
        messageBodyEntityDaoConfig.initIdentityScope(type);

        senderEntityDaoConfig = daoConfigMap.get(SenderEntityDao.class).clone();
        senderEntityDaoConfig.initIdentityScope(type);

        tagEntityDaoConfig = daoConfigMap.get(TagEntityDao.class).clone();
        tagEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        articleEntityDaoConfig = daoConfigMap.get(ArticleEntityDao.class).clone();
        articleEntityDaoConfig.initIdentityScope(type);

        imageEntityDaoConfig = daoConfigMap.get(ImageEntityDao.class).clone();
        imageEntityDaoConfig.initIdentityScope(type);

        attendanceEntityDaoConfig = daoConfigMap.get(AttendanceEntityDao.class).clone();
        attendanceEntityDaoConfig.initIdentityScope(type);

        festivalEntityDaoConfig = daoConfigMap.get(FestivalEntityDao.class).clone();
        festivalEntityDaoConfig.initIdentityScope(type);

        scheduleEntityDaoConfig = daoConfigMap.get(ScheduleEntityDao.class).clone();
        scheduleEntityDaoConfig.initIdentityScope(type);

        lastLetterEntityDaoConfig = daoConfigMap.get(LastLetterEntityDao.class).clone();
        lastLetterEntityDaoConfig.initIdentityScope(type);

        letterEntityDaoConfig = daoConfigMap.get(LetterEntityDao.class).clone();
        letterEntityDaoConfig.initIdentityScope(type);

        reportEntityDaoConfig = daoConfigMap.get(ReportEntityDao.class).clone();
        reportEntityDaoConfig.initIdentityScope(type);

        reportItemEntityDaoConfig = daoConfigMap.get(ReportItemEntityDao.class).clone();
        reportItemEntityDaoConfig.initIdentityScope(type);

        configEntityDao = new ConfigEntityDao(configEntityDaoConfig, this);
        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);
        classEntityDao = new ClassEntityDao(classEntityDaoConfig, this);
        schoolEntityDao = new SchoolEntityDao(schoolEntityDaoConfig, this);
        messageBodyEntityDao = new MessageBodyEntityDao(messageBodyEntityDaoConfig, this);
        senderEntityDao = new SenderEntityDao(senderEntityDaoConfig, this);
        tagEntityDao = new TagEntityDao(tagEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        articleEntityDao = new ArticleEntityDao(articleEntityDaoConfig, this);
        imageEntityDao = new ImageEntityDao(imageEntityDaoConfig, this);
        attendanceEntityDao = new AttendanceEntityDao(attendanceEntityDaoConfig, this);
        festivalEntityDao = new FestivalEntityDao(festivalEntityDaoConfig, this);
        scheduleEntityDao = new ScheduleEntityDao(scheduleEntityDaoConfig, this);
        lastLetterEntityDao = new LastLetterEntityDao(lastLetterEntityDaoConfig, this);
        letterEntityDao = new LetterEntityDao(letterEntityDaoConfig, this);
        reportEntityDao = new ReportEntityDao(reportEntityDaoConfig, this);
        reportItemEntityDao = new ReportItemEntityDao(reportItemEntityDaoConfig, this);

        registerDao(ConfigEntity.class, configEntityDao);
        registerDao(StudentEntity.class, studentEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
        registerDao(ClassEntity.class, classEntityDao);
        registerDao(SchoolEntity.class, schoolEntityDao);
        registerDao(MessageBodyEntity.class, messageBodyEntityDao);
        registerDao(SenderEntity.class, senderEntityDao);
        registerDao(TagEntity.class, tagEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(ArticleEntity.class, articleEntityDao);
        registerDao(ImageEntity.class, imageEntityDao);
        registerDao(AttendanceEntity.class, attendanceEntityDao);
        registerDao(FestivalEntity.class, festivalEntityDao);
        registerDao(ScheduleEntity.class, scheduleEntityDao);
        registerDao(LastLetterEntity.class, lastLetterEntityDao);
        registerDao(LetterEntity.class, letterEntityDao);
        registerDao(ReportEntity.class, reportEntityDao);
        registerDao(ReportItemEntity.class, reportItemEntityDao);
    }
    
    public void clear() {
        configEntityDaoConfig.getIdentityScope().clear();
        studentEntityDaoConfig.getIdentityScope().clear();
        teacherEntityDaoConfig.getIdentityScope().clear();
        classEntityDaoConfig.getIdentityScope().clear();
        schoolEntityDaoConfig.getIdentityScope().clear();
        messageBodyEntityDaoConfig.getIdentityScope().clear();
        senderEntityDaoConfig.getIdentityScope().clear();
        tagEntityDaoConfig.getIdentityScope().clear();
        messageEntityDaoConfig.getIdentityScope().clear();
        articleEntityDaoConfig.getIdentityScope().clear();
        imageEntityDaoConfig.getIdentityScope().clear();
        attendanceEntityDaoConfig.getIdentityScope().clear();
        festivalEntityDaoConfig.getIdentityScope().clear();
        scheduleEntityDaoConfig.getIdentityScope().clear();
        lastLetterEntityDaoConfig.getIdentityScope().clear();
        letterEntityDaoConfig.getIdentityScope().clear();
        reportEntityDaoConfig.getIdentityScope().clear();
        reportItemEntityDaoConfig.getIdentityScope().clear();
    }

    public ConfigEntityDao getConfigEntityDao() {
        return configEntityDao;
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

    public ClassEntityDao getClassEntityDao() {
        return classEntityDao;
    }

    public SchoolEntityDao getSchoolEntityDao() {
        return schoolEntityDao;
    }

    public MessageBodyEntityDao getMessageBodyEntityDao() {
        return messageBodyEntityDao;
    }

    public SenderEntityDao getSenderEntityDao() {
        return senderEntityDao;
    }

    public TagEntityDao getTagEntityDao() {
        return tagEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public ArticleEntityDao getArticleEntityDao() {
        return articleEntityDao;
    }

    public ImageEntityDao getImageEntityDao() {
        return imageEntityDao;
    }

    public AttendanceEntityDao getAttendanceEntityDao() {
        return attendanceEntityDao;
    }

    public FestivalEntityDao getFestivalEntityDao() {
        return festivalEntityDao;
    }

    public ScheduleEntityDao getScheduleEntityDao() {
        return scheduleEntityDao;
    }

    public LastLetterEntityDao getLastLetterEntityDao() {
        return lastLetterEntityDao;
    }

    public LetterEntityDao getLetterEntityDao() {
        return letterEntityDao;
    }

    public ReportEntityDao getReportEntityDao() {
        return reportEntityDao;
    }

    public ReportItemEntityDao getReportItemEntityDao() {
        return reportItemEntityDao;
    }

}
