package com.guokrspace.cloudschoolbus.parents.database.daodb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configEntityDaoConfig;
    private final DaoConfig studentEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;
    private final DaoConfig classEntityDaoConfig;
    private final DaoConfig schoolEntityDaoConfig;
    private final DaoConfig schoolEntityTDaoConfig;
    private final DaoConfig classEntityTDaoConfig;
    private final DaoConfig studentEntityTDaoConfig;
    private final DaoConfig parentEntityTDaoConfig;
    private final DaoConfig teacherEntityTDaoConfig;
    private final DaoConfig tagsEntityTDaoConfig;
    private final DaoConfig messageTypeEntityDaoConfig;
    private final DaoConfig classModuleEntityDaoConfig;
    private final DaoConfig teacherDutyEntityDaoConfig;
    private final DaoConfig teacherDutyClassRelationEntityDaoConfig;
    private final DaoConfig studentClassRelationEntityDaoConfig;
    private final DaoConfig studentParentRelationEntityDaoConfig;
    private final DaoConfig uploadArticleEntityDaoConfig;
    private final DaoConfig uploadArticleFileEntityDaoConfig;
    private final DaoConfig lastIMMessageEntityDaoConfig;
    private final DaoConfig senderEntityDaoConfig;
    private final DaoConfig tagEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig articleEntityDaoConfig;
    private final DaoConfig imageEntityDaoConfig;
    private final DaoConfig attendanceEntityDaoConfig;
    private final DaoConfig festivalEntityDaoConfig;
    private final DaoConfig scheduleEntityDaoConfig;
    private final DaoConfig lastLetterEntityDaoConfig;
    private final DaoConfig letterEntityDaoConfig;
    private final DaoConfig reportEntityDaoConfig;
    private final DaoConfig reportItemEntityDaoConfig;

    private final ConfigEntityDao configEntityDao;
    private final StudentEntityDao studentEntityDao;
    private final TeacherEntityDao teacherEntityDao;
    private final ClassEntityDao classEntityDao;
    private final SchoolEntityDao schoolEntityDao;
    private final SchoolEntityTDao schoolEntityTDao;
    private final ClassEntityTDao classEntityTDao;
    private final StudentEntityTDao studentEntityTDao;
    private final ParentEntityTDao parentEntityTDao;
    private final TeacherEntityTDao teacherEntityTDao;
    private final TagsEntityTDao tagsEntityTDao;
    private final MessageTypeEntityDao messageTypeEntityDao;
    private final ClassModuleEntityDao classModuleEntityDao;
    private final TeacherDutyEntityDao teacherDutyEntityDao;
    private final TeacherDutyClassRelationEntityDao teacherDutyClassRelationEntityDao;
    private final StudentClassRelationEntityDao studentClassRelationEntityDao;
    private final StudentParentRelationEntityDao studentParentRelationEntityDao;
    private final UploadArticleEntityDao uploadArticleEntityDao;
    private final UploadArticleFileEntityDao uploadArticleFileEntityDao;
    private final LastIMMessageEntityDao lastIMMessageEntityDao;
    private final SenderEntityDao senderEntityDao;
    private final TagEntityDao tagEntityDao;
    private final MessageEntityDao messageEntityDao;
    private final ArticleEntityDao articleEntityDao;
    private final ImageEntityDao imageEntityDao;
    private final AttendanceEntityDao attendanceEntityDao;
    private final FestivalEntityDao festivalEntityDao;
    private final ScheduleEntityDao scheduleEntityDao;
    private final LastLetterEntityDao lastLetterEntityDao;
    private final LetterEntityDao letterEntityDao;
    private final ReportEntityDao reportEntityDao;
    private final ReportItemEntityDao reportItemEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configEntityDaoConfig = daoConfigMap.get(ConfigEntityDao.class).clone();
        configEntityDaoConfig.initIdentityScope(type);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        classEntityDaoConfig = daoConfigMap.get(ClassEntityDao.class).clone();
        classEntityDaoConfig.initIdentityScope(type);

        schoolEntityDaoConfig = daoConfigMap.get(SchoolEntityDao.class).clone();
        schoolEntityDaoConfig.initIdentityScope(type);

        schoolEntityTDaoConfig = daoConfigMap.get(SchoolEntityTDao.class).clone();
        schoolEntityTDaoConfig.initIdentityScope(type);

        classEntityTDaoConfig = daoConfigMap.get(ClassEntityTDao.class).clone();
        classEntityTDaoConfig.initIdentityScope(type);

        studentEntityTDaoConfig = daoConfigMap.get(StudentEntityTDao.class).clone();
        studentEntityTDaoConfig.initIdentityScope(type);

        parentEntityTDaoConfig = daoConfigMap.get(ParentEntityTDao.class).clone();
        parentEntityTDaoConfig.initIdentityScope(type);

        teacherEntityTDaoConfig = daoConfigMap.get(TeacherEntityTDao.class).clone();
        teacherEntityTDaoConfig.initIdentityScope(type);

        tagsEntityTDaoConfig = daoConfigMap.get(TagsEntityTDao.class).clone();
        tagsEntityTDaoConfig.initIdentityScope(type);

        messageTypeEntityDaoConfig = daoConfigMap.get(MessageTypeEntityDao.class).clone();
        messageTypeEntityDaoConfig.initIdentityScope(type);

        classModuleEntityDaoConfig = daoConfigMap.get(ClassModuleEntityDao.class).clone();
        classModuleEntityDaoConfig.initIdentityScope(type);

        teacherDutyEntityDaoConfig = daoConfigMap.get(TeacherDutyEntityDao.class).clone();
        teacherDutyEntityDaoConfig.initIdentityScope(type);

        teacherDutyClassRelationEntityDaoConfig = daoConfigMap.get(TeacherDutyClassRelationEntityDao.class).clone();
        teacherDutyClassRelationEntityDaoConfig.initIdentityScope(type);

        studentClassRelationEntityDaoConfig = daoConfigMap.get(StudentClassRelationEntityDao.class).clone();
        studentClassRelationEntityDaoConfig.initIdentityScope(type);

        studentParentRelationEntityDaoConfig = daoConfigMap.get(StudentParentRelationEntityDao.class).clone();
        studentParentRelationEntityDaoConfig.initIdentityScope(type);

        uploadArticleEntityDaoConfig = daoConfigMap.get(UploadArticleEntityDao.class).clone();
        uploadArticleEntityDaoConfig.initIdentityScope(type);

        uploadArticleFileEntityDaoConfig = daoConfigMap.get(UploadArticleFileEntityDao.class).clone();
        uploadArticleFileEntityDaoConfig.initIdentityScope(type);

        lastIMMessageEntityDaoConfig = daoConfigMap.get(LastIMMessageEntityDao.class).clone();
        lastIMMessageEntityDaoConfig.initIdentityScope(type);

        senderEntityDaoConfig = daoConfigMap.get(SenderEntityDao.class).clone();
        senderEntityDaoConfig.initIdentityScope(type);

        tagEntityDaoConfig = daoConfigMap.get(TagEntityDao.class).clone();
        tagEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        articleEntityDaoConfig = daoConfigMap.get(ArticleEntityDao.class).clone();
        articleEntityDaoConfig.initIdentityScope(type);

        imageEntityDaoConfig = daoConfigMap.get(ImageEntityDao.class).clone();
        imageEntityDaoConfig.initIdentityScope(type);

        attendanceEntityDaoConfig = daoConfigMap.get(AttendanceEntityDao.class).clone();
        attendanceEntityDaoConfig.initIdentityScope(type);

        festivalEntityDaoConfig = daoConfigMap.get(FestivalEntityDao.class).clone();
        festivalEntityDaoConfig.initIdentityScope(type);

        scheduleEntityDaoConfig = daoConfigMap.get(ScheduleEntityDao.class).clone();
        scheduleEntityDaoConfig.initIdentityScope(type);

        lastLetterEntityDaoConfig = daoConfigMap.get(LastLetterEntityDao.class).clone();
        lastLetterEntityDaoConfig.initIdentityScope(type);

        letterEntityDaoConfig = daoConfigMap.get(LetterEntityDao.class).clone();
        letterEntityDaoConfig.initIdentityScope(type);

        reportEntityDaoConfig = daoConfigMap.get(ReportEntityDao.class).clone();
        reportEntityDaoConfig.initIdentityScope(type);

        reportItemEntityDaoConfig = daoConfigMap.get(ReportItemEntityDao.class).clone();
        reportItemEntityDaoConfig.initIdentityScope(type);

        configEntityDao = new ConfigEntityDao(configEntityDaoConfig, this);
        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);
        classEntityDao = new ClassEntityDao(classEntityDaoConfig, this);
        schoolEntityDao = new SchoolEntityDao(schoolEntityDaoConfig, this);
        schoolEntityTDao = new SchoolEntityTDao(schoolEntityTDaoConfig, this);
        classEntityTDao = new ClassEntityTDao(classEntityTDaoConfig, this);
        studentEntityTDao = new StudentEntityTDao(studentEntityTDaoConfig, this);
        parentEntityTDao = new ParentEntityTDao(parentEntityTDaoConfig, this);
        teacherEntityTDao = new TeacherEntityTDao(teacherEntityTDaoConfig, this);
        tagsEntityTDao = new TagsEntityTDao(tagsEntityTDaoConfig, this);
        messageTypeEntityDao = new MessageTypeEntityDao(messageTypeEntityDaoConfig, this);
        classModuleEntityDao = new ClassModuleEntityDao(classModuleEntityDaoConfig, this);
        teacherDutyEntityDao = new TeacherDutyEntityDao(teacherDutyEntityDaoConfig, this);
        teacherDutyClassRelationEntityDao = new TeacherDutyClassRelationEntityDao(teacherDutyClassRelationEntityDaoConfig, this);
        studentClassRelationEntityDao = new StudentClassRelationEntityDao(studentClassRelationEntityDaoConfig, this);
        studentParentRelationEntityDao = new StudentParentRelationEntityDao(studentParentRelationEntityDaoConfig, this);
        uploadArticleEntityDao = new UploadArticleEntityDao(uploadArticleEntityDaoConfig, this);
        uploadArticleFileEntityDao = new UploadArticleFileEntityDao(uploadArticleFileEntityDaoConfig, this);
        lastIMMessageEntityDao = new LastIMMessageEntityDao(lastIMMessageEntityDaoConfig, this);
        senderEntityDao = new SenderEntityDao(senderEntityDaoConfig, this);
        tagEntityDao = new TagEntityDao(tagEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        articleEntityDao = new ArticleEntityDao(articleEntityDaoConfig, this);
        imageEntityDao = new ImageEntityDao(imageEntityDaoConfig, this);
        attendanceEntityDao = new AttendanceEntityDao(attendanceEntityDaoConfig, this);
        festivalEntityDao = new FestivalEntityDao(festivalEntityDaoConfig, this);
        scheduleEntityDao = new ScheduleEntityDao(scheduleEntityDaoConfig, this);
        lastLetterEntityDao = new LastLetterEntityDao(lastLetterEntityDaoConfig, this);
        letterEntityDao = new LetterEntityDao(letterEntityDaoConfig, this);
        reportEntityDao = new ReportEntityDao(reportEntityDaoConfig, this);
        reportItemEntityDao = new ReportItemEntityDao(reportItemEntityDaoConfig, this);

        registerDao(ConfigEntity.class, configEntityDao);
        registerDao(StudentEntity.class, studentEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
        registerDao(ClassEntity.class, classEntityDao);
        registerDao(SchoolEntity.class, schoolEntityDao);
        registerDao(SchoolEntityT.class, schoolEntityTDao);
        registerDao(ClassEntityT.class, classEntityTDao);
        registerDao(StudentEntityT.class, studentEntityTDao);
        registerDao(ParentEntityT.class, parentEntityTDao);
        registerDao(TeacherEntityT.class, teacherEntityTDao);
        registerDao(TagsEntityT.class, tagsEntityTDao);
        registerDao(MessageTypeEntity.class, messageTypeEntityDao);
        registerDao(ClassModuleEntity.class, classModuleEntityDao);
        registerDao(TeacherDutyEntity.class, teacherDutyEntityDao);
        registerDao(TeacherDutyClassRelationEntity.class, teacherDutyClassRelationEntityDao);
        registerDao(StudentClassRelationEntity.class, studentClassRelationEntityDao);
        registerDao(StudentParentRelationEntity.class, studentParentRelationEntityDao);
        registerDao(UploadArticleEntity.class, uploadArticleEntityDao);
        registerDao(UploadArticleFileEntity.class, uploadArticleFileEntityDao);
        registerDao(LastIMMessageEntity.class, lastIMMessageEntityDao);
        registerDao(SenderEntity.class, senderEntityDao);
        registerDao(TagEntity.class, tagEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(ArticleEntity.class, articleEntityDao);
        registerDao(ImageEntity.class, imageEntityDao);
        registerDao(AttendanceEntity.class, attendanceEntityDao);
        registerDao(FestivalEntity.class, festivalEntityDao);
        registerDao(ScheduleEntity.class, scheduleEntityDao);
        registerDao(LastLetterEntity.class, lastLetterEntityDao);
        registerDao(LetterEntity.class, letterEntityDao);
        registerDao(ReportEntity.class, reportEntityDao);
        registerDao(ReportItemEntity.class, reportItemEntityDao);
    }
    
    public void clear() {
        configEntityDaoConfig.getIdentityScope().clear();
        studentEntityDaoConfig.getIdentityScope().clear();
        teacherEntityDaoConfig.getIdentityScope().clear();
        classEntityDaoConfig.getIdentityScope().clear();
        schoolEntityDaoConfig.getIdentityScope().clear();
        schoolEntityTDaoConfig.getIdentityScope().clear();
        classEntityTDaoConfig.getIdentityScope().clear();
        studentEntityTDaoConfig.getIdentityScope().clear();
        parentEntityTDaoConfig.getIdentityScope().clear();
        teacherEntityTDaoConfig.getIdentityScope().clear();
        tagsEntityTDaoConfig.getIdentityScope().clear();
        messageTypeEntityDaoConfig.getIdentityScope().clear();
        classModuleEntityDaoConfig.getIdentityScope().clear();
        teacherDutyEntityDaoConfig.getIdentityScope().clear();
        teacherDutyClassRelationEntityDaoConfig.getIdentityScope().clear();
        studentClassRelationEntityDaoConfig.getIdentityScope().clear();
        studentParentRelationEntityDaoConfig.getIdentityScope().clear();
        uploadArticleEntityDaoConfig.getIdentityScope().clear();
        uploadArticleFileEntityDaoConfig.getIdentityScope().clear();
        lastIMMessageEntityDaoConfig.getIdentityScope().clear();
        senderEntityDaoConfig.getIdentityScope().clear();
        tagEntityDaoConfig.getIdentityScope().clear();
        messageEntityDaoConfig.getIdentityScope().clear();
        articleEntityDaoConfig.getIdentityScope().clear();
        imageEntityDaoConfig.getIdentityScope().clear();
        attendanceEntityDaoConfig.getIdentityScope().clear();
        festivalEntityDaoConfig.getIdentityScope().clear();
        scheduleEntityDaoConfig.getIdentityScope().clear();
        lastLetterEntityDaoConfig.getIdentityScope().clear();
        letterEntityDaoConfig.getIdentityScope().clear();
        reportEntityDaoConfig.getIdentityScope().clear();
        reportItemEntityDaoConfig.getIdentityScope().clear();
    }

    public ConfigEntityDao getConfigEntityDao() {
        return configEntityDao;
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

    public ClassEntityDao getClassEntityDao() {
        return classEntityDao;
    }

    public SchoolEntityDao getSchoolEntityDao() {
        return schoolEntityDao;
    }

    public SchoolEntityTDao getSchoolEntityTDao() {
        return schoolEntityTDao;
    }

    public ClassEntityTDao getClassEntityTDao() {
        return classEntityTDao;
    }

    public StudentEntityTDao getStudentEntityTDao() {
        return studentEntityTDao;
    }

    public ParentEntityTDao getParentEntityTDao() {
        return parentEntityTDao;
    }

    public TeacherEntityTDao getTeacherEntityTDao() {
        return teacherEntityTDao;
    }

    public TagsEntityTDao getTagsEntityTDao() {
        return tagsEntityTDao;
    }

    public MessageTypeEntityDao getMessageTypeEntityDao() {
        return messageTypeEntityDao;
    }

    public ClassModuleEntityDao getClassModuleEntityDao() {
        return classModuleEntityDao;
    }

    public TeacherDutyEntityDao getTeacherDutyEntityDao() {
        return teacherDutyEntityDao;
    }

    public TeacherDutyClassRelationEntityDao getTeacherDutyClassRelationEntityDao() {
        return teacherDutyClassRelationEntityDao;
    }

    public StudentClassRelationEntityDao getStudentClassRelationEntityDao() {
        return studentClassRelationEntityDao;
    }

    public StudentParentRelationEntityDao getStudentParentRelationEntityDao() {
        return studentParentRelationEntityDao;
    }

    public UploadArticleEntityDao getUploadArticleEntityDao() {
        return uploadArticleEntityDao;
    }

    public UploadArticleFileEntityDao getUploadArticleFileEntityDao() {
        return uploadArticleFileEntityDao;
    }

    public LastIMMessageEntityDao getLastIMMessageEntityDao() {
        return lastIMMessageEntityDao;
    }

    public SenderEntityDao getSenderEntityDao() {
        return senderEntityDao;
    }

    public TagEntityDao getTagEntityDao() {
        return tagEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public ArticleEntityDao getArticleEntityDao() {
        return articleEntityDao;
    }

    public ImageEntityDao getImageEntityDao() {
        return imageEntityDao;
    }

    public AttendanceEntityDao getAttendanceEntityDao() {
        return attendanceEntityDao;
    }

    public FestivalEntityDao getFestivalEntityDao() {
        return festivalEntityDao;
    }

    public ScheduleEntityDao getScheduleEntityDao() {
        return scheduleEntityDao;
    }

    public LastLetterEntityDao getLastLetterEntityDao() {
        return lastLetterEntityDao;
    }

    public LetterEntityDao getLetterEntityDao() {
        return letterEntityDao;
    }

    public ReportEntityDao getReportEntityDao() {
        return reportEntityDao;
    }

    public ReportItemEntityDao getReportItemEntityDao() {
        return reportItemEntityDao;
    }

}
