package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DUTY_IN_CLASS_ENTITY.
 */
public class DutyInClassEntity {

    private String classid;
    private String dutyid;
    private String duty;

    public DutyInClassEntity() {
    }

    public DutyInClassEntity(String classid, String dutyid, String duty) {
        this.classid = classid;
        this.dutyid = dutyid;
        this.duty = duty;
    }

    public String getClassid() {
        return classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getDutyid() {
        return dutyid;
    }

    public void setDutyid(String dutyid) {
        this.dutyid = dutyid;
    }

    public String getDuty() {
        return duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

}
