package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAST_LETTER_ENTITY.
 */
public class LastLetterEntity {

    /** Not-null value. */
    private String teacherid;
    private String lastchat;
    private String picture;

    public LastLetterEntity() {
    }

    public LastLetterEntity(String teacherid) {
        this.teacherid = teacherid;
    }

    public LastLetterEntity(String teacherid, String lastchat, String picture) {
        this.teacherid = teacherid;
        this.lastchat = lastchat;
        this.picture = picture;
    }

    /** Not-null value. */
    public String getTeacherid() {
        return teacherid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid;
    }

    public String getLastchat() {
        return lastchat;
    }

    public void setLastchat(String lastchat) {
        this.lastchat = lastchat;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

}
