package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAST_IMMESSAGE_ENTITY.
 */
public class LastIMMessageEntity {

    private Long id;
    private String timestamp;
    private String hasUnread;
    /** Not-null value. */
    private String userid;

    public LastIMMessageEntity() {
    }

    public LastIMMessageEntity(Long id) {
        this.id = id;
    }

    public LastIMMessageEntity(Long id, String timestamp, String hasUnread, String userid) {
        this.id = id;
        this.timestamp = timestamp;
        this.hasUnread = hasUnread;
        this.userid = userid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getHasUnread() {
        return hasUnread;
    }

    public void setHasUnread(String hasUnread) {
        this.hasUnread = hasUnread;
    }

    /** Not-null value. */
    public String getUserid() {
        return userid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserid(String userid) {
        this.userid = userid;
    }

}
