package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAST_IMMESSAGE_ENTITY.
 */
public class LastIMMessageEntity {

    /** Not-null value. */
    private String teacherid;
    private String timestamp;
    private String hasUnread;

    public LastIMMessageEntity() {
    }

    public LastIMMessageEntity(String teacherid) {
        this.teacherid = teacherid;
    }

    public LastIMMessageEntity(String teacherid, String timestamp, String hasUnread) {
        this.teacherid = teacherid;
        this.timestamp = timestamp;
        this.hasUnread = hasUnread;
    }

    /** Not-null value. */
    public String getTeacherid() {
        return teacherid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getHasUnread() {
        return hasUnread;
    }

    public void setHasUnread(String hasUnread) {
        this.hasUnread = hasUnread;
    }

}
