package com.guokrspace.cloudschoolbus.parents.database.daodb;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table LAST_IMMESSAGE_ENTITY.
*/
public class LastIMMessageEntityDao extends AbstractDao<LastIMMessageEntity, Long> {

    public static final String TABLENAME = "LAST_IMMESSAGE_ENTITY";

    /**
     * Properties of entity LastIMMessageEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Timestamp = new Property(1, String.class, "timestamp", false, "TIMESTAMP");
        public final static Property HasUnread = new Property(2, String.class, "hasUnread", false, "HAS_UNREAD");
        public final static Property Userid = new Property(3, String.class, "userid", false, "USERID");
    };

    private Query<LastIMMessageEntity> teacherEntity_LastIMMessageEntityListQuery;
    private Query<LastIMMessageEntity> parentEntityT_LastIMMessageEntityListQuery;
    private Query<LastIMMessageEntity> teacherEntityT_LastIMMessageEntityListQuery;

    public LastIMMessageEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LastIMMessageEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LAST_IMMESSAGE_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TIMESTAMP' TEXT," + // 1: timestamp
                "'HAS_UNREAD' TEXT," + // 2: hasUnread
                "'USERID' TEXT NOT NULL );"); // 3: userid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LAST_IMMESSAGE_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LastIMMessageEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindString(2, timestamp);
        }
 
        String hasUnread = entity.getHasUnread();
        if (hasUnread != null) {
            stmt.bindString(3, hasUnread);
        }
        stmt.bindString(4, entity.getUserid());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LastIMMessageEntity readEntity(Cursor cursor, int offset) {
        LastIMMessageEntity entity = new LastIMMessageEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // timestamp
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hasUnread
            cursor.getString(offset + 3) // userid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LastIMMessageEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTimestamp(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHasUnread(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserid(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LastIMMessageEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LastIMMessageEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "lastIMMessageEntityList" to-many relationship of TeacherEntity. */
    public List<LastIMMessageEntity> _queryTeacherEntity_LastIMMessageEntityList(String userid) {
        synchronized (this) {
            if (teacherEntity_LastIMMessageEntityListQuery == null) {
                QueryBuilder<LastIMMessageEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Userid.eq(null));
                teacherEntity_LastIMMessageEntityListQuery = queryBuilder.build();
            }
        }
        Query<LastIMMessageEntity> query = teacherEntity_LastIMMessageEntityListQuery.forCurrentThread();
        query.setParameter(0, userid);
        return query.list();
    }

    /** Internal query to resolve the "lastIMMessageEntityList" to-many relationship of ParentEntityT. */
    public List<LastIMMessageEntity> _queryParentEntityT_LastIMMessageEntityList(String userid) {
        synchronized (this) {
            if (parentEntityT_LastIMMessageEntityListQuery == null) {
                QueryBuilder<LastIMMessageEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Userid.eq(null));
                parentEntityT_LastIMMessageEntityListQuery = queryBuilder.build();
            }
        }
        Query<LastIMMessageEntity> query = parentEntityT_LastIMMessageEntityListQuery.forCurrentThread();
        query.setParameter(0, userid);
        return query.list();
    }

    /** Internal query to resolve the "lastIMMessageEntityList" to-many relationship of TeacherEntityT. */
    public List<LastIMMessageEntity> _queryTeacherEntityT_LastIMMessageEntityList(String userid) {
        synchronized (this) {
            if (teacherEntityT_LastIMMessageEntityListQuery == null) {
                QueryBuilder<LastIMMessageEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Userid.eq(null));
                teacherEntityT_LastIMMessageEntityListQuery = queryBuilder.build();
            }
        }
        Query<LastIMMessageEntity> query = teacherEntityT_LastIMMessageEntityListQuery.forCurrentThread();
        query.setParameter(0, userid);
        return query.list();
    }

}
