package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARENT_ENTITY_T.
 */
public class ParentEntityT {

    /** Not-null value. */
    private String parentid;
    private String nikename;
    private String relationship;
    private String mobile;
    private String avatar;

    public ParentEntityT() {
    }

    public ParentEntityT(String parentid) {
        this.parentid = parentid;
    }

    public ParentEntityT(String parentid, String nikename, String relationship, String mobile, String avatar) {
        this.parentid = parentid;
        this.nikename = nikename;
        this.relationship = relationship;
        this.mobile = mobile;
        this.avatar = avatar;
    }

    /** Not-null value. */
    public String getParentid() {
        return parentid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public String getNikename() {
        return nikename;
    }

    public void setNikename(String nikename) {
        this.nikename = nikename;
    }

    public String getRelationship() {
        return relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

}
