package com.guokrspace.cloudschoolbus.parents.database.daodb;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SCHOOL_ENTITY_T.
 */
public class SchoolEntityT {

    /** Not-null value. */
    private String id;
    private String groupid;
    private String name;
    private String groudid;
    private String remark;
    private String address;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SchoolEntityTDao myDao;

    private List<ClassEntityT> classEntityTList;
    private List<SettingsEntityT> settingsEntityTList;
    private List<TagsEntityT> tagsEntityTList;

    public SchoolEntityT() {
    }

    public SchoolEntityT(String id) {
        this.id = id;
    }

    public SchoolEntityT(String id, String groupid, String name, String groudid, String remark, String address) {
        this.id = id;
        this.groupid = groupid;
        this.name = name;
        this.groudid = groudid;
        this.remark = remark;
        this.address = address;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSchoolEntityTDao() : null;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getGroupid() {
        return groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGroudid() {
        return groudid;
    }

    public void setGroudid(String groudid) {
        this.groudid = groudid;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ClassEntityT> getClassEntityTList() {
        if (classEntityTList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ClassEntityTDao targetDao = daoSession.getClassEntityTDao();
            List<ClassEntityT> classEntityTListNew = targetDao._querySchoolEntityT_ClassEntityTList(id);
            synchronized (this) {
                if(classEntityTList == null) {
                    classEntityTList = classEntityTListNew;
                }
            }
        }
        return classEntityTList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetClassEntityTList() {
        classEntityTList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SettingsEntityT> getSettingsEntityTList() {
        if (settingsEntityTList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SettingsEntityTDao targetDao = daoSession.getSettingsEntityTDao();
            List<SettingsEntityT> settingsEntityTListNew = targetDao._querySchoolEntityT_SettingsEntityTList(id);
            synchronized (this) {
                if(settingsEntityTList == null) {
                    settingsEntityTList = settingsEntityTListNew;
                }
            }
        }
        return settingsEntityTList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSettingsEntityTList() {
        settingsEntityTList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<TagsEntityT> getTagsEntityTList() {
        if (tagsEntityTList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TagsEntityTDao targetDao = daoSession.getTagsEntityTDao();
            List<TagsEntityT> tagsEntityTListNew = targetDao._querySchoolEntityT_TagsEntityTList(id);
            synchronized (this) {
                if(tagsEntityTList == null) {
                    tagsEntityTList = tagsEntityTListNew;
                }
            }
        }
        return tagsEntityTList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTagsEntityTList() {
        tagsEntityTList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
