package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETTINGS_ENTITY_T.
 */
public class SettingsEntityT {

    private String id;
    private String message_type;
    private String class_module;
    /** Not-null value. */
    private String schoolid;

    public SettingsEntityT() {
    }

    public SettingsEntityT(String id) {
        this.id = id;
    }

    public SettingsEntityT(String id, String message_type, String class_module, String schoolid) {
        this.id = id;
        this.message_type = message_type;
        this.class_module = class_module;
        this.schoolid = schoolid;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage_type() {
        return message_type;
    }

    public void setMessage_type(String message_type) {
        this.message_type = message_type;
    }

    public String getClass_module() {
        return class_module;
    }

    public void setClass_module(String class_module) {
        this.class_module = class_module;
    }

    /** Not-null value. */
    public String getSchoolid() {
        return schoolid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
