package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_ENTITY.
 */
public class StudentEntity {

    private String cnname;
    private String birthday;
    private String sex;
    private String avatar;
    private String nikename;
    /** Not-null value. */
    private String studentid;
    /** Not-null value. */
    private String classid;

    public StudentEntity() {
    }

    public StudentEntity(String studentid) {
        this.studentid = studentid;
    }

    public StudentEntity(String cnname, String birthday, String sex, String avatar, String nikename, String studentid, String classid) {
        this.cnname = cnname;
        this.birthday = birthday;
        this.sex = sex;
        this.avatar = avatar;
        this.nikename = nikename;
        this.studentid = studentid;
        this.classid = classid;
    }

    public String getCnname() {
        return cnname;
    }

    public void setCnname(String cnname) {
        this.cnname = cnname;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getNikename() {
        return nikename;
    }

    public void setNikename(String nikename) {
        this.nikename = nikename;
    }

    /** Not-null value. */
    public String getStudentid() {
        return studentid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    /** Not-null value. */
    public String getClassid() {
        return classid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassid(String classid) {
        this.classid = classid;
    }

}
