package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_PARENT_RELATION_ENTITY.
 */
public class StudentParentRelationEntity {

    private String studentid;
    private String parentid;

    public StudentParentRelationEntity() {
    }

    public StudentParentRelationEntity(String studentid, String parentid) {
        this.studentid = studentid;
        this.parentid = parentid;
    }

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    public String getParentid() {
        return parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

}
