package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_ENTITY_T.
 */
public class StudentEntityT {

    /** Not-null value. */
    private String studentid;
    private String nikename;
    private String cnname;
    private String sex;
    private String birthday;
    private String avatar;

    public StudentEntityT() {
    }

    public StudentEntityT(String studentid) {
        this.studentid = studentid;
    }

    public StudentEntityT(String studentid, String nikename, String cnname, String sex, String birthday, String avatar) {
        this.studentid = studentid;
        this.nikename = nikename;
        this.cnname = cnname;
        this.sex = sex;
        this.birthday = birthday;
        this.avatar = avatar;
    }

    /** Not-null value. */
    public String getStudentid() {
        return studentid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    public String getNikename() {
        return nikename;
    }

    public void setNikename(String nikename) {
        this.nikename = nikename;
    }

    public String getCnname() {
        return cnname;
    }

    public void setCnname(String cnname) {
        this.cnname = cnname;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

}
