package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_ENTITY.
 */
public class StudentEntity {

    /** Not-null value. */
    private String uid_student;
    private String uid_class;
    private String inactive;
    private String birthday;
    private String cnname;
    private String nikename;
    private String sex;
    private String classname;
    private String schoolid;

    public StudentEntity() {
    }

    public StudentEntity(String uid_student, String uid_class, String inactive, String birthday, String cnname, String nikename, String sex, String classname, String schoolid) {
        this.uid_student = uid_student;
        this.uid_class = uid_class;
        this.inactive = inactive;
        this.birthday = birthday;
        this.cnname = cnname;
        this.nikename = nikename;
        this.sex = sex;
        this.classname = classname;
        this.schoolid = schoolid;
    }

    /** Not-null value. */
    public String getUid_student() {
        return uid_student;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid_student(String uid_student) {
        this.uid_student = uid_student;
    }

    public String getUid_class() {
        return uid_class;
    }

    public void setUid_class(String uid_class) {
        this.uid_class = uid_class;
    }

    public String getInactive() {
        return inactive;
    }

    public void setInactive(String inactive) {
        this.inactive = inactive;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getCnname() {
        return cnname;
    }

    public void setCnname(String cnname) {
        this.cnname = cnname;
    }

    public String getNikename() {
        return nikename;
    }

    public void setNikename(String nikename) {
        this.nikename = nikename;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname = classname;
    }

    public String getSchoolid() {
        return schoolid;
    }

    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
