package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_CLASS_RELATION_ENTITY.
 */
public class StudentClassRelationEntity {

    private String studentid;
    private String classid;

    public StudentClassRelationEntity() {
    }

    public StudentClassRelationEntity(String studentid, String classid) {
        this.studentid = studentid;
        this.classid = classid;
    }

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    public String getClassid() {
        return classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

}
