package com.guokrspace.cloudschoolbus.parents.database.daodb;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table TEACHER_ENTITY.
*/
public class TeacherEntityDao extends AbstractDao<TeacherEntity, String> {

    public static final String TABLENAME = "TEACHER_ENTITY";

    /**
     * Properties of entity TeacherEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Teacherid = new Property(0, String.class, "teacherid", true, "TEACHERID");
        public final static Property Teachername = new Property(1, String.class, "teachername", false, "TEACHERNAME");
        public final static Property Classid = new Property(2, String.class, "classid", false, "CLASSID");
    };

    private Query<TeacherEntity> classEntity_TeacherEntityListQuery;

    public TeacherEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TEACHER_ENTITY' (" + //
                "'TEACHERID' TEXT PRIMARY KEY NOT NULL ," + // 0: teacherid
                "'TEACHERNAME' TEXT," + // 1: teachername
                "'CLASSID' TEXT NOT NULL );"); // 2: classid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TEACHER_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TeacherEntity entity) {
        stmt.clearBindings();
 
        String teacherid = entity.getTeacherid();
        if (teacherid != null) {
            stmt.bindString(1, teacherid);
        }
 
        String teachername = entity.getTeachername();
        if (teachername != null) {
            stmt.bindString(2, teachername);
        }
        stmt.bindString(3, entity.getClassid());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TeacherEntity readEntity(Cursor cursor, int offset) {
        TeacherEntity entity = new TeacherEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // teacherid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // teachername
            cursor.getString(offset + 2) // classid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TeacherEntity entity, int offset) {
        entity.setTeacherid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTeachername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setClassid(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(TeacherEntity entity, long rowId) {
        return entity.getTeacherid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(TeacherEntity entity) {
        if(entity != null) {
            return entity.getTeacherid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teacherEntityList" to-many relationship of ClassEntity. */
    public List<TeacherEntity> _queryClassEntity_TeacherEntityList(String classid) {
        synchronized (this) {
            if (classEntity_TeacherEntityListQuery == null) {
                QueryBuilder<TeacherEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Classid.eq(null));
                classEntity_TeacherEntityListQuery = queryBuilder.build();
            }
        }
        Query<TeacherEntity> query = classEntity_TeacherEntityListQuery.forCurrentThread();
        query.setParameter(0, classid);
        return query.list();
    }

}
