package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table TEACHER_ENTITY_T.
 */
public class TeacherEntityT implements Serializable{

    /** Not-null value. */
    private String teacherid;
    private String duty;
    private String avatar;
    private String realname;
    private String nickname;
    private String sex;
    private String mobile;
    /** Not-null value. */
    private String schoolid;

    public TeacherEntityT() {
    }

    public TeacherEntityT(String teacherid) {
        this.teacherid = teacherid;
    }

    public TeacherEntityT(String teacherid, String duty, String avatar, String realname, String nickname, String sex, String mobile, String schoolid) {
        this.teacherid = teacherid;
        this.duty = duty;
        this.avatar = avatar;
        this.realname = realname;
        this.nickname = nickname;
        this.sex = sex;
        this.mobile = mobile;
        this.schoolid = schoolid;
    }

    /** Not-null value. */
    public String getTeacherid() {
        return teacherid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid;
    }

    public String getDuty() {
        return duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /** Not-null value. */
    public String getSchoolid() {
        return schoolid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
