package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEACHER_DUTY_ENTITY.
 */
public class TeacherDutyEntity {

    /** Not-null value. */
    private String id;
    private String duty;
    /** Not-null value. */
    private String schoolid;

    public TeacherDutyEntity() {
    }

    public TeacherDutyEntity(String id) {
        this.id = id;
    }

    public TeacherDutyEntity(String id, String duty, String schoolid) {
        this.id = id;
        this.duty = duty;
        this.schoolid = schoolid;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getDuty() {
        return duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

    /** Not-null value. */
    public String getSchoolid() {
        return schoolid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
