package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table UPLOAD_ARTICLE_FILE_ENTITY.
 */
public class UploadArticleFileEntity {

    private Long id;
    private byte[] fbody;
    private String fname;
    private String ftime;
    private String pictype;
    private Boolean isSuccess;
    /** Not-null value. */
    private String pickey;

    public UploadArticleFileEntity() {
    }

    public UploadArticleFileEntity(Long id) {
        this.id = id;
    }

    public UploadArticleFileEntity(Long id, byte[] fbody, String fname, String ftime, String pictype, Boolean isSuccess, String pickey) {
        this.id = id;
        this.fbody = fbody;
        this.fname = fname;
        this.ftime = ftime;
        this.pictype = pictype;
        this.isSuccess = isSuccess;
        this.pickey = pickey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getFbody() {
        return fbody;
    }

    public void setFbody(byte[] fbody) {
        this.fbody = fbody;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getFtime() {
        return ftime;
    }

    public void setFtime(String ftime) {
        this.ftime = ftime;
    }

    public String getPictype() {
        return pictype;
    }

    public void setPictype(String pictype) {
        this.pictype = pictype;
    }

    public Boolean getIsSuccess() {
        return isSuccess;
    }

    public void setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /** Not-null value. */
    public String getPickey() {
        return pickey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPickey(String pickey) {
        this.pickey = pickey;
    }

}
