package com.guokrspace.cloudschoolbus.parents.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table UPLOADING_PHOTO_ENTITY.
 */
public class UploadingPhotoEntity {

    /** Not-null value. */
    private String key;
    private String picPathString;
    private String picFileString;
    private String picSizeString;
    private String studentId;
    private String classuid;
    private String intro;
    private String photoTag;
    private String teacherid;

    public UploadingPhotoEntity() {
    }

    public UploadingPhotoEntity(String key) {
        this.key = key;
    }

    public UploadingPhotoEntity(String key, String picPathString, String picFileString, String picSizeString, String studentId, String classuid, String intro, String photoTag, String teacherid) {
        this.key = key;
        this.picPathString = picPathString;
        this.picFileString = picFileString;
        this.picSizeString = picSizeString;
        this.studentId = studentId;
        this.classuid = classuid;
        this.intro = intro;
        this.photoTag = photoTag;
        this.teacherid = teacherid;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public String getPicPathString() {
        return picPathString;
    }

    public void setPicPathString(String picPathString) {
        this.picPathString = picPathString;
    }

    public String getPicFileString() {
        return picFileString;
    }

    public void setPicFileString(String picFileString) {
        this.picFileString = picFileString;
    }

    public String getPicSizeString() {
        return picSizeString;
    }

    public void setPicSizeString(String picSizeString) {
        this.picSizeString = picSizeString;
    }

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getClassuid() {
        return classuid;
    }

    public void setClassuid(String classuid) {
        this.classuid = classuid;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getPhotoTag() {
        return photoTag;
    }

    public void setPhotoTag(String photoTag) {
        this.photoTag = photoTag;
    }

    public String getTeacherid() {
        return teacherid;
    }

    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid;
    }

}
