package com.guokrspace.cloudschoolbus.teacher.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLASS_ENTITY_T.
 */
public class ClassEntityT {

    /** Not-null value. */
    private String classid;
    private String classname;
    private String remark;
    private String dutyid;
    /** Not-null value. */
    private String schoolid;

    public ClassEntityT() {
    }

    public ClassEntityT(String classid) {
        this.classid = classid;
    }

    public ClassEntityT(String classid, String classname, String remark, String dutyid, String schoolid) {
        this.classid = classid;
        this.classname = classname;
        this.remark = remark;
        this.dutyid = dutyid;
        this.schoolid = schoolid;
    }

    /** Not-null value. */
    public String getClassid() {
        return classid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname = classname;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDutyid() {
        return dutyid;
    }

    public void setDutyid(String dutyid) {
        this.dutyid = dutyid;
    }

    /** Not-null value. */
    public String getSchoolid() {
        return schoolid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
