package com.guokrspace.cloudschoolbus.teacher.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_TYPE_ENTITY.
 */
public class MessageTypeEntity {

    /** Not-null value. */
    private String id;
    private String type;
    /** Not-null value. */
    private String schoolid;

    public MessageTypeEntity() {
    }

    public MessageTypeEntity(String id) {
        this.id = id;
    }

    public MessageTypeEntity(String id, String type, String schoolid) {
        this.id = id;
        this.type = type;
        this.schoolid = schoolid;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getSchoolid() {
        return schoolid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid;
    }

}
