package com.guokrspace.cloudschoolbus.teacher.database.daodb;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table MESSAGE_TYPE_ENTITY.
*/
public class MessageTypeEntityDao extends AbstractDao<MessageTypeEntity, String> {

    public static final String TABLENAME = "MESSAGE_TYPE_ENTITY";

    /**
     * Properties of entity MessageTypeEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Schoolid = new Property(2, String.class, "schoolid", false, "SCHOOLID");
    };

    private Query<MessageTypeEntity> schoolEntityT_MessageTypeEntityListQuery;

    public MessageTypeEntityDao(DaoConfig config) {
        super(config);
    }
    
    public MessageTypeEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MESSAGE_TYPE_ENTITY' (" + //
                "'ID' TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "'TYPE' TEXT," + // 1: type
                "'SCHOOLID' TEXT NOT NULL );"); // 2: schoolid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MESSAGE_TYPE_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MessageTypeEntity entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindString(3, entity.getSchoolid());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MessageTypeEntity readEntity(Cursor cursor, int offset) {
        MessageTypeEntity entity = new MessageTypeEntity( //
            cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.getString(offset + 2) // schoolid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MessageTypeEntity entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSchoolid(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(MessageTypeEntity entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(MessageTypeEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "messageTypeEntityList" to-many relationship of SchoolEntityT. */
    public List<MessageTypeEntity> _querySchoolEntityT_MessageTypeEntityList(String schoolid) {
        synchronized (this) {
            if (schoolEntityT_MessageTypeEntityListQuery == null) {
                QueryBuilder<MessageTypeEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Schoolid.eq(null));
                schoolEntityT_MessageTypeEntityListQuery = queryBuilder.build();
            }
        }
        Query<MessageTypeEntity> query = schoolEntityT_MessageTypeEntityListQuery.forCurrentThread();
        query.setParameter(0, schoolid);
        return query.list();
    }

}
