package com.guokrspace.cloudschoolbus.teacher.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REPORT_ITEM_ENTITY.
 */
public class ReportItemEntity {

    private String title;
    private String answer;
    /** Not-null value. */
    private String reportId;

    public ReportItemEntity() {
    }

    public ReportItemEntity(String title, String answer, String reportId) {
        this.title = title;
        this.answer = answer;
        this.reportId = reportId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /** Not-null value. */
    public String getReportId() {
        return reportId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

}
