package com.guokrspace.cloudschoolbus.teacher.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCHEDULE_ENTITY.
 */
public class ScheduleEntity {

    private Integer starthour;
    private Integer startmin;
    private Integer endhour;
    private Integer endmin;
    private String cnname;
    private String enname;
    private Integer week;
    private Integer year;

    public ScheduleEntity() {
    }

    public ScheduleEntity(Integer starthour, Integer startmin, Integer endhour, Integer endmin, String cnname, String enname, Integer week, Integer year) {
        this.starthour = starthour;
        this.startmin = startmin;
        this.endhour = endhour;
        this.endmin = endmin;
        this.cnname = cnname;
        this.enname = enname;
        this.week = week;
        this.year = year;
    }

    public Integer getStarthour() {
        return starthour;
    }

    public void setStarthour(Integer starthour) {
        this.starthour = starthour;
    }

    public Integer getStartmin() {
        return startmin;
    }

    public void setStartmin(Integer startmin) {
        this.startmin = startmin;
    }

    public Integer getEndhour() {
        return endhour;
    }

    public void setEndhour(Integer endhour) {
        this.endhour = endhour;
    }

    public Integer getEndmin() {
        return endmin;
    }

    public void setEndmin(Integer endmin) {
        this.endmin = endmin;
    }

    public String getCnname() {
        return cnname;
    }

    public void setCnname(String cnname) {
        this.cnname = cnname;
    }

    public String getEnname() {
        return enname;
    }

    public void setEnname(String enname) {
        this.enname = enname;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

}
