package com.guokrspace.cloudschoolbus.teacher.database.daodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.support.annotation.Nullable;

/**
 * Entity mapped to table UPLOAD_ARTICLE_FILE_ENTITY.
 */
public class UploadArticleFileEntity {

    private Long id;
    private String fbody;
    private String thumb;
    private String compress;
    private String fname;
    private String ftime;
    private String pictype;
    private Boolean isSuccess;
    /** Not-null value. */
    private String pickey;

    public UploadArticleFileEntity() {
    }

    public UploadArticleFileEntity(Long id) {
        this.id = id;
    }

    public UploadArticleFileEntity(Long id, String fbody, String thumb, String compress, String fname, String ftime, String pictype, Boolean isSuccess, String pickey) {
        this.id = id;
        this.fbody = fbody;
        this.thumb = thumb;
        this.compress = compress;
        this.fname = fname;
        this.ftime = ftime;
        this.pictype = pictype;
        this.isSuccess = isSuccess;
        this.pickey = pickey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFbody() {
        return fbody;
    }

    public void setFbody(String fbody) {
        this.fbody = fbody;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getCompress() {
        return compress;
    }

    public void setCompress(String compress) {
        this.compress = compress;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getFtime() {
        return ftime;
    }

    public void setFtime(String ftime) {
        this.ftime = ftime;
    }

    public String getPictype() {
        return pictype;
    }

    public void setPictype(String pictype) {
        this.pictype = pictype;
    }

    public Boolean getIsSuccess() {
        return isSuccess;
    }

    // Null：Not started True: success False: Fail or in progress
    public void setIsSuccess(@Nullable Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /** Not-null value. */
    public String getPickey() {
        return pickey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPickey(String pickey) {
        this.pickey = pickey;
    }

}
